"""Cognitive Inference Engine -- multi-signal Bayesian fusion + extreme guessing.

When evidence is sparse (one detection, one trail, a magnitude bump in an
empty patch of sky), traditional discovery pipelines say "insufficient data."
This engine instead computes a posterior distribution over competing
HYPOTHESES, ranked by the cumulative evidence available, and returns the
most-educated guess WITH its uncertainty.

Architecture:

  1. Evidence ingestion: take any combination of Source(s), tracklet(s),
     candidate(s), multi-band photometry, sky-context.
  2. Hypothesis generation: enumerate physically-plausible explanations.
     The hypothesis SPACE is generated by walking taxonomy classes (NEO/MBA/
     Trojan/Centaur/TNO/Comet/Artefact/etc.) and the morphology classes
     (POINT/EXTENDED/STREAK/BLEND/COSMIC_RAY).
  3. Free-energy scoring: each hypothesis pays a "complexity cost" (prior
     under the dynamical population model) + an "accuracy cost" (how well it
     explains the observations). Lower free energy = better.
  4. Posterior: softmax over free-energies -> probability distribution.
  5. Episodic recall: query the candidate store for past detections with
     similar (position, rate, color). Memory acts as a prior.
  6. Active inference: recommend the NEXT observation that would maximally
     reduce uncertainty over the top hypotheses.
  7. Pareto ranking: when multiple objectives matter (probability * novelty
     * follow-up cost), the Pareto front gives the best trade-offs.
  8. Predictive scheduler: learns from past confirmation/rejection outcomes
     which observation strategy maximises information gain for each
     hypothesis class. Adaptive over time.

The engine COMPOSES (not replaces) every classifier/scorer/predictor module:
morphology, colors, taxonomy, realbogus, scoring, followup. It is the
brain that ties them.

Output: an InferenceResult containing ranked hypotheses, predicted next
positions, recommended follow-up, and human-readable explanations.

References:
  - Friston 2010 (free-energy principle); Friston & FitzGerald 2017 (active
    inference).
  - Granvik & Brown 2018 (NEO population model); Petit et al. 2011 (TNO
    population priors); Bowell 1989 (asteroid taxonomic priors).
  - Holman et al. 2018 (HelioLinC sparse-data linker).
"""
from __future__ import annotations

import math
import statistics
from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from . import colors as colors_mod
from . import realbogus
from . import scoring as scoring_mod
from . import taxonomy
from .operations.candidate_store import Candidate, CandidateStore


# ============================================================================
# Evidence types
# ============================================================================

@dataclass
class Evidence:
    """Container for ANY combination of available evidence on one (or several)
    putative objects. Every field is optional; the engine works with whatever
    is provided.

    Fields:
      mjd:                   epoch of the most recent observation.
      ra_deg, dec_deg:       sky position (most recent or single observation).
      rate_arcsec_hr:        on-sky angular rate, if known.
      apparent_mag:          most recent observed magnitude.
      band:                  photometric band character (g, r, i, z, V).
      band_magnitudes:       full multi-band dict (e.g. {"g":21.5, "r":20.9}).
      morphology_label:      a MorphologyClass label, if image-pipeline ran.
      morphology_confidence: associated confidence (0..1).
      n_detections:          count of independent detections.
      arc_days:              span of the arc, days.
      rms_arcsec:            orbit-fit RMS if a fit was attempted.
      orbit_state:           fitted [x,y,z,vx,vy,vz] heliocentric km/km/s.
      skybot_match_names:    SkyBoT cross-match results, empty list if checked
                              and clean, None if not checked.
      sky_context:           extra dict for any sidereal context (galactic
                              latitude, field crowding, etc.).
    """
    mjd: Optional[float] = None
    ra_deg: Optional[float] = None
    dec_deg: Optional[float] = None
    rate_arcsec_hr: Optional[float] = None
    apparent_mag: Optional[float] = None
    band: Optional[str] = None
    band_magnitudes: dict = field(default_factory=dict)
    morphology_label: Optional[str] = None
    morphology_confidence: Optional[float] = None
    n_detections: int = 1
    arc_days: float = 0.0
    rms_arcsec: Optional[float] = None
    orbit_state: Optional[list] = None
    skybot_match_names: Optional[list] = None
    sky_context: dict = field(default_factory=dict)


# ============================================================================
# Hypothesis types
# ============================================================================

@dataclass
class Hypothesis:
    """One explanation for the evidence, with priors + per-likelihood scores.

    Fields:
      label:             human-readable name (e.g. "TNO 50 AU", "NEO Apollo",
                          "satellite trail", "cosmic ray", "stellar variable").
      class_:            broad category: "moving_object", "transient", "artefact",
                          "stellar".
      orbital_class:     OrbitClass.* label if class_ == "moving_object".
      morphology_class:  MorphologyClass.* label expected.
      prior:             log p(H) -- prior probability under the population model.
      likelihood:        log p(E|H) -- how well evidence fits the hypothesis.
      free_energy:       F = -log p(H) - log p(E|H); LOWER is better.
      posterior:         p(H|E) -- normalised over the hypothesis space.
      predicted_motion_arcsec_hr:  rate this hypothesis EXPECTS.
      predicted_size_km:           rough size from magnitude + assumed albedo.
      predicted_distance_au:       rough heliocentric distance.
      explanation:       free-text 'why this hypothesis fits' for humans.
    """
    label: str
    class_: str = "unknown"
    orbital_class: Optional[str] = None
    morphology_class: Optional[str] = None
    prior: float = 0.0                  # log prior
    likelihood: float = 0.0             # log likelihood
    free_energy: float = float("inf")
    posterior: float = 0.0
    predicted_motion_arcsec_hr: Optional[float] = None
    predicted_size_km: Optional[float] = None
    predicted_distance_au: Optional[float] = None
    explanation: str = ""


@dataclass
class InferenceResult:
    """Output of one inference cycle on a piece of Evidence.

    Fields:
      hypotheses:               list of Hypothesis ordered by free_energy
                                 (best first). posterior sums to 1.
      best:                     hypothesis with highest posterior.
      entropy:                  Shannon entropy of the posterior (high =
                                 ambiguous; low = confident).
      recommended_followup:     dict {action, observation_target, expected_info_gain}
      memory_matches:           list of Candidate from the store that resemble
                                 this evidence (episodic recall).
      pareto_front:             multi-objective optimal hypotheses (probability,
                                 novelty, low follow-up cost).
      narrative:                human-readable summary of the inference.
    """
    hypotheses: list
    best: Optional[Hypothesis] = None
    entropy: float = float("inf")
    recommended_followup: dict = field(default_factory=dict)
    memory_matches: list = field(default_factory=list)
    pareto_front: list = field(default_factory=list)
    narrative: str = ""


# ============================================================================
# Priors (population-model based)
# ============================================================================

# Approximate fractions of detected moving objects by class (Granvik+ NEO,
# MPC catalogue for MBAs, Petit+ for TNOs). These are PRIORS -- the cumulative
# evidence then overrides them. Values sum to 1.0.
DEFAULT_CLASS_PRIORS = {
    "MBA": 0.65,           # the dominant population
    "IMB": 0.10,
    "OMB": 0.05,
    "AMOR": 0.04,
    "APOLLO": 0.03,
    "ATEN": 0.005,
    "ATIRA": 0.001,
    "MARS_CROSSER": 0.015,
    "HILDA": 0.005,
    "JTROJAN": 0.04,
    "CENTAUR": 0.001,
    "CLASSICAL_KBO": 0.003,
    "HOT_CLASSICAL": 0.005,
    "RESONANT_KBO": 0.002,
    "SCATTERED_KBO": 0.002,
    "DETACHED": 0.0005,
    "SEDNOID": 0.0001,
    "COMET_HYPERBOLIC": 0.001,
}

# Artefact priors -- how often each spurious class shows up in a typical pipeline
# run, conditional on a detection passing the simple filters. These are NOT
# class priors of MOVING objects; they're priors over the whole hypothesis space
# (moving objects + artefacts + transients).
ARTEFACT_PRIORS = {
    "satellite_trail": 0.10,
    "cosmic_ray": 0.05,
    "stellar_variable": 0.05,
    "supernova_or_agn": 0.02,
    "subtraction_residual": 0.10,
    "edge_artefact": 0.03,
    "blend_two_stars": 0.05,
    "ghost_or_diffraction": 0.02,
}

# Expected on-sky rates (arcsec/hr) by class. Used for likelihood (a class with
# expected_rate=1 doesn't fit evidence showing rate=30).
EXPECTED_RATES = {
    "MBA":            (5.0, 25.0),
    "IMB":            (8.0, 30.0),
    "OMB":            (3.0, 18.0),
    "AMOR":           (10.0, 120.0),
    "APOLLO":         (15.0, 600.0),
    "ATEN":           (15.0, 600.0),
    "ATIRA":          (10.0, 200.0),
    "MARS_CROSSER":   (8.0, 60.0),
    "HILDA":          (2.0, 10.0),
    "JTROJAN":        (2.0, 8.0),
    "CENTAUR":        (1.0, 5.0),
    "CLASSICAL_KBO":  (0.3, 3.0),
    "HOT_CLASSICAL":  (0.3, 3.0),
    "RESONANT_KBO":   (0.4, 3.5),
    "SCATTERED_KBO":  (0.4, 3.5),
    "DETACHED":       (0.2, 2.0),
    "SEDNOID":        (0.05, 1.0),
    "COMET_HYPERBOLIC": (1.0, 200.0),
}

# Typical heliocentric distance by class (AU)
TYPICAL_DISTANCES = {
    "MBA": 2.7, "IMB": 2.2, "OMB": 3.4,
    "AMOR": 1.5, "APOLLO": 1.5, "ATEN": 0.9, "ATIRA": 0.8,
    "MARS_CROSSER": 2.0, "HILDA": 4.0, "JTROJAN": 5.2,
    "CENTAUR": 15.0,
    "CLASSICAL_KBO": 44.0, "HOT_CLASSICAL": 44.0,
    "RESONANT_KBO": 39.4, "SCATTERED_KBO": 60.0,
    "DETACHED": 80.0, "SEDNOID": 500.0,
    "COMET_HYPERBOLIC": 10.0,
}


# ============================================================================
# Likelihood functions (how well each hypothesis fits evidence)
# ============================================================================

def _gaussian_log_pdf(x: float, mu: float, sigma: float) -> float:
    """Log of N(mu, sigma) density at x. Clipped to prevent -inf."""
    if sigma <= 0:
        return -1e6
    z = (x - mu) / sigma
    return -0.5 * z * z - math.log(sigma * math.sqrt(2 * math.pi))


def _uniform_log_pdf_in_range(x: float, lo: float, hi: float,
                              soft_outside_pct: float = 0.2) -> float:
    """Log-uniform inside [lo, hi], with soft exponential decay outside.

    soft_outside_pct controls how quickly the density falls when x leaves the
    range: at lo*(1-soft), the log-pdf drops by 1 below the in-range value.
    """
    if lo <= x <= hi:
        return -math.log(max(hi - lo, 1e-6))
    width = hi - lo
    if width <= 0:
        return -1e6
    if x < lo:
        d = (lo - x) / max(width * soft_outside_pct, 1e-6)
    else:
        d = (x - hi) / max(width * soft_outside_pct, 1e-6)
    return -math.log(width) - d * d


def _rate_log_likelihood(observed_rate: float, class_name: str) -> float:
    """How well the observed on-sky rate fits the expected rate for this class.

    Aggressive out-of-range penalty (soft_outside_pct=0.10): a rate that's
    way outside the class's expected window strongly down-weights that class,
    even against a large prior. Empirically calibrated so a TNO-rate (1"/hr)
    correctly out-competes the MBA prior for genuine TNO evidence.
    """
    if class_name not in EXPECTED_RATES:
        return -2.0
    lo, hi = EXPECTED_RATES[class_name]
    return _uniform_log_pdf_in_range(observed_rate, lo, hi, soft_outside_pct=0.10)


def _magnitude_log_likelihood(observed_mag: float, class_name: str,
                              expected_distance_au: float) -> float:
    """Distance + size prior under H(mag, distance, albedo).

    For a class with typical distance D, expected size range S, albedo A:
      apparent_mag ~ H + 5 log10(D * delta) where delta ~= D (opposition)
      H = absolute mag = -5 log10(D_sun) - 5 log10(D_obs) + apparent
    We score the consistency: large objects + close distances are bright;
    if the observed mag is way out of the expected range for the class,
    likelihood drops.
    """
    if not math.isfinite(observed_mag) or observed_mag < 0 or observed_mag > 35:
        return -2.0
    # Quick magnitude-distance check: NEOs at V<15, MBAs at V<19, TNOs at V>20
    if class_name in ("ATIRA", "ATEN", "APOLLO", "AMOR"):
        return _uniform_log_pdf_in_range(observed_mag, 10.0, 22.0, soft_outside_pct=0.3)
    if class_name in ("MBA", "IMB", "OMB", "MARS_CROSSER"):
        return _uniform_log_pdf_in_range(observed_mag, 15.0, 22.0, soft_outside_pct=0.3)
    if class_name in ("HILDA", "JTROJAN"):
        return _uniform_log_pdf_in_range(observed_mag, 16.0, 22.5, soft_outside_pct=0.3)
    if class_name == "CENTAUR":
        return _uniform_log_pdf_in_range(observed_mag, 18.0, 23.0, soft_outside_pct=0.3)
    if class_name in ("CLASSICAL_KBO", "HOT_CLASSICAL", "RESONANT_KBO",
                      "SCATTERED_KBO", "DETACHED", "SEDNOID"):
        return _uniform_log_pdf_in_range(observed_mag, 19.0, 25.0, soft_outside_pct=0.3)
    if class_name == "COMET_HYPERBOLIC":
        return _uniform_log_pdf_in_range(observed_mag, 14.0, 23.0, soft_outside_pct=0.4)
    return -1.0


def _morphology_log_likelihood(observed_label: str, observed_conf: float,
                                expected_label: str) -> float:
    """How well the morphology matches the hypothesis's expected morphology."""
    if observed_label == expected_label:
        return math.log(max(observed_conf, 0.05))
    # any moving-object hypothesis EXPECTS POINT; if observed is BLEND, that's
    # a possible match (one of the components might be the asteroid).
    if expected_label == "POINT" and observed_label == "BLEND":
        return math.log(0.30)
    # Streaks indicate fast NEOs or satellites
    if observed_label == "STREAK" and expected_label == "POINT":
        return math.log(0.10)
    return math.log(max(0.05, 1.0 - observed_conf))


def _orbit_state_log_likelihood(orbit_state: list, class_name: str) -> float:
    """If we have a fitted orbit, the orbital class derived from it should match."""
    if orbit_state is None or len(orbit_state) != 6:
        return 0.0
    try:
        r = np.asarray(orbit_state[:3])
        v = np.asarray(orbit_state[3:])
        tax = taxonomy.classify_state(r, v)
        if tax.label == class_name:
            return math.log(max(tax.confidence, 0.05))
        return math.log(0.10)
    except Exception:
        return -1.0


# ============================================================================
# Hypothesis generation (over moving-object classes + artefact classes)
# ============================================================================

def _generate_moving_object_hypotheses(evidence: Evidence,
                                       class_priors: dict) -> list[Hypothesis]:
    """One hypothesis per orbital class (NEO/MBA/Trojan/Centaur/TNO/etc.)."""
    hyps = []
    for class_name, prior_frac in class_priors.items():
        prior = math.log(max(prior_frac, 1e-9))
        likelihood = 0.0
        n_terms = 0

        if evidence.rate_arcsec_hr is not None:
            likelihood += _rate_log_likelihood(evidence.rate_arcsec_hr, class_name)
            n_terms += 1

        dist = TYPICAL_DISTANCES.get(class_name, 5.0)
        if evidence.apparent_mag is not None:
            likelihood += _magnitude_log_likelihood(
                evidence.apparent_mag, class_name, dist)
            n_terms += 1

        if evidence.morphology_label is not None:
            likelihood += _morphology_log_likelihood(
                evidence.morphology_label,
                evidence.morphology_confidence or 0.5,
                "POINT",
            )
            n_terms += 1

        if evidence.orbit_state is not None:
            likelihood += _orbit_state_log_likelihood(
                evidence.orbit_state, class_name)
            n_terms += 1

        # If SkyBoT confirmed clean (empty list), bump prior slightly for
        # rare classes (TNO finds + comet discoveries are the prize).
        if evidence.skybot_match_names is not None and not evidence.skybot_match_names:
            if class_name in ("SEDNOID", "DETACHED", "RESONANT_KBO",
                              "COMET_HYPERBOLIC"):
                prior += math.log(2.0)

        # If a strong RMS fit exists, weight likelihood up
        if evidence.rms_arcsec is not None and math.isfinite(evidence.rms_arcsec):
            if evidence.rms_arcsec < 3.0:
                likelihood += math.log(2.0)
            elif evidence.rms_arcsec > 15.0:
                likelihood += math.log(0.5)
        # NOTE: do NOT normalise likelihood by sqrt(n_terms): more evidence
        # should accumulate MORE log-likelihood. Normalising hides discriminating
        # power (a strict rate mismatch deserves a strong penalty regardless of
        # how many other evidence terms exist).

        rate_lo, rate_hi = EXPECTED_RATES.get(class_name, (0, 10))
        hyps.append(Hypothesis(
            label=f"{class_name} ({dist:.0f} AU)",
            class_="moving_object",
            orbital_class=class_name,
            morphology_class="POINT",
            prior=prior,
            likelihood=likelihood,
            free_energy=-(prior + likelihood),
            predicted_motion_arcsec_hr=(rate_lo + rate_hi) / 2.0,
            predicted_distance_au=dist,
            predicted_size_km=_size_from_magnitude(evidence.apparent_mag, dist)
                              if evidence.apparent_mag else None,
            explanation=(f"Class {class_name}: prior {prior_frac*100:.2f}%, "
                          f"expected rate {rate_lo}-{rate_hi} arcsec/hr at "
                          f"{dist} AU."),
        ))
    return hyps


def _generate_artefact_hypotheses(evidence: Evidence,
                                  artefact_priors: dict) -> list[Hypothesis]:
    """One hypothesis per artefact category.

    Artefacts have STRONG anti-evidence rules: a multi-night arc with low RMS
    and many independent re-detections cannot physically be a cosmic ray,
    subtraction residual, or single-image artefact. The likelihood includes
    those penalties so the engine ranks artefacts correctly even when no
    positive evidence (morphology label, extreme rate) is present.
    """
    hyps = []

    # GLOBAL anti-evidence: NO artefact class in this set produces a coherent
    # multi-night moving arc. A long-baseline arc with low RMS and consistent
    # proper motion EXCLUDES every spurious class.
    single_image_penalty = 0.0     # penalty for single-frame artefacts only
    if evidence.n_detections >= 3:
        single_image_penalty -= 2.0 * (evidence.n_detections - 2)
    if evidence.arc_days >= 3.0:
        single_image_penalty -= 1.0 * min(evidence.arc_days / 3.0, 5.0)
    if (evidence.rms_arcsec is not None and math.isfinite(evidence.rms_arcsec)
            and evidence.rms_arcsec < 5.0 and evidence.n_detections >= 4):
        single_image_penalty -= 3.0

    # NONE of the artefact classes naturally generate consistent multi-night
    # proper motion. If the evidence shows >0.2"/hr motion across >=3 detections,
    # penalize every artefact heavily.
    multinight_motion_penalty = 0.0
    if (evidence.rate_arcsec_hr is not None and evidence.rate_arcsec_hr > 0.2
            and evidence.n_detections >= 3 and evidence.arc_days >= 1.0):
        multinight_motion_penalty -= 3.0 * min(evidence.n_detections, 8) / 4.0
        if (evidence.rms_arcsec is not None and evidence.rms_arcsec < 3.0):
            multinight_motion_penalty -= 4.0

    for label, prior_frac in artefact_priors.items():
        prior = math.log(max(prior_frac, 1e-9))
        likelihood = multinight_motion_penalty
        explanation = f"Artefact class {label}, prior {prior_frac*100:.1f}%."

        # Single-frame artefacts also get the n_detections penalty
        if label in ("cosmic_ray", "subtraction_residual", "edge_artefact",
                     "ghost_or_diffraction"):
            likelihood += single_image_penalty

        # cosmic_ray: strong likelihood if morphology says so + low rate
        if label == "cosmic_ray":
            if evidence.morphology_label == "COSMIC_RAY":
                likelihood += math.log(0.9 * (evidence.morphology_confidence or 0.5))
            elif evidence.morphology_label == "POINT":
                likelihood += math.log(0.05)
            if evidence.n_detections == 1:
                likelihood += math.log(2.0)        # cosmic rays don't repeat

        # satellite_trail: VERY high rate + 1-night
        elif label == "satellite_trail":
            if evidence.rate_arcsec_hr is not None and evidence.rate_arcsec_hr > 1000:
                likelihood += math.log(0.9)
            if evidence.morphology_label == "STREAK":
                likelihood += math.log(0.95 * (evidence.morphology_confidence or 0.5))

        # stellar_variable: zero motion + position matches a known star catalogue
        elif label == "stellar_variable":
            if evidence.rate_arcsec_hr is not None and evidence.rate_arcsec_hr < 0.05:
                likelihood += math.log(0.8)
            else:
                likelihood += math.log(0.05)

        # supernova_or_agn: zero motion + galaxy-class position
        elif label == "supernova_or_agn":
            if evidence.rate_arcsec_hr is not None and evidence.rate_arcsec_hr < 0.05:
                likelihood += math.log(0.5)
            if evidence.morphology_label == "EXTENDED":
                likelihood += math.log(0.8)
            else:
                likelihood += math.log(0.1)

        # subtraction_residual: dipole-like patterns -> high RMS, low n_detections
        elif label == "subtraction_residual":
            if evidence.n_detections == 1:
                likelihood += math.log(0.5)
            if evidence.rms_arcsec is not None and evidence.rms_arcsec > 20:
                likelihood += math.log(0.7)

        # edge_artefact: morphology says so
        elif label == "edge_artefact":
            if evidence.morphology_label == "EDGE_ARTEFACT":
                likelihood += math.log(0.95 * (evidence.morphology_confidence or 0.5))

        # blend_two_stars: morphology BLEND + zero motion
        elif label == "blend_two_stars":
            if evidence.morphology_label == "BLEND":
                likelihood += math.log(0.5)
            if evidence.rate_arcsec_hr is not None and evidence.rate_arcsec_hr < 0.1:
                likelihood += math.log(0.7)

        else:
            # generic artefact prior, no evidence-specific boost. Use += so the
            # multinight_motion_penalty already accumulated stays in effect.
            likelihood += math.log(0.2)

        hyps.append(Hypothesis(
            label=label, class_="artefact",
            prior=prior, likelihood=likelihood,
            free_energy=-(prior + likelihood),
            explanation=explanation,
        ))
    return hyps


def _size_from_magnitude(V_mag: float, distance_au: float,
                         albedo: float = 0.10) -> float:
    """Rough size estimate (km) from apparent magnitude assuming a typical albedo.

    H = V - 5 log10(r * delta) + correction; here we collapse to r ~ delta and
    use the standard D = 1329 / sqrt(albedo) * 10^(-0.2 H) kilometres.
    """
    if V_mag is None or not math.isfinite(V_mag) or distance_au <= 0:
        return float("nan")
    # absolute mag H -- delta = r at opposition, near-circular geometry
    H = V_mag - 5 * math.log10(distance_au) - 5 * math.log10(distance_au - 1.0
                                                              if distance_au > 1 else 1)
    D_km = 1329.0 / math.sqrt(max(albedo, 0.02)) * 10 ** (-0.2 * H)
    return D_km


# ============================================================================
# Posterior normalisation, entropy, narrative
# ============================================================================

def _normalise_posterior(hypotheses: list[Hypothesis]):
    """Convert free-energy values to a normalised posterior distribution.

    Uses softmax(-F) for numerical stability against very wide free-energy ranges.
    """
    if not hypotheses:
        return
    # subtract the min so the largest -F is 0 (stability)
    min_F = min(h.free_energy for h in hypotheses if math.isfinite(h.free_energy))
    weights = []
    for h in hypotheses:
        if not math.isfinite(h.free_energy):
            weights.append(0.0)
        else:
            weights.append(math.exp(-(h.free_energy - min_F)))
    total = sum(weights)
    if total <= 0:
        for h in hypotheses:
            h.posterior = 1.0 / len(hypotheses)
        return
    for h, w in zip(hypotheses, weights):
        h.posterior = w / total


def _shannon_entropy(probs: list[float]) -> float:
    """H = -sum p_i log p_i in nats."""
    s = 0.0
    for p in probs:
        if p > 0:
            s -= p * math.log(p)
    return s


def _build_narrative(result: InferenceResult, evidence: Evidence) -> str:
    """Produce a human-readable summary of the inference."""
    if not result.hypotheses:
        return "No hypotheses generated."
    best = result.best
    second = result.hypotheses[1] if len(result.hypotheses) > 1 else None

    lines = []
    if best.posterior > 0.6:
        lines.append(f"HIGH-CONFIDENCE: {best.label} ({best.posterior*100:.0f}%).")
    elif best.posterior > 0.35:
        lines.append(f"LEADING HYPOTHESIS: {best.label} ({best.posterior*100:.0f}%); "
                     f"runner-up {second.label if second else 'n/a'} "
                     f"({second.posterior*100:.0f}% if second else 0).")
    else:
        lines.append(f"AMBIGUOUS: top guess {best.label} only "
                     f"{best.posterior*100:.0f}%; evidence is sparse "
                     f"(entropy {result.entropy:.2f} nats).")

    # Evidence summary
    parts = []
    if evidence.rate_arcsec_hr is not None:
        parts.append(f"rate {evidence.rate_arcsec_hr:.2f}\"/hr")
    if evidence.apparent_mag is not None:
        parts.append(f"mag {evidence.apparent_mag:.1f}")
    if evidence.morphology_label is not None:
        parts.append(f"morph {evidence.morphology_label}")
    if evidence.skybot_match_names is not None and not evidence.skybot_match_names:
        parts.append("no SkyBoT match")
    if evidence.n_detections > 1:
        parts.append(f"{evidence.n_detections} detections over {evidence.arc_days:.1f}d")
    if parts:
        lines.append(f"  Evidence: {', '.join(parts)}.")

    # Top-3 ranking
    lines.append(f"  Top hypotheses:")
    for h in result.hypotheses[:3]:
        lines.append(f"    {h.posterior*100:>5.1f}%  {h.label:<28s}  ({h.explanation[:64]})")

    if result.recommended_followup:
        f = result.recommended_followup
        lines.append(f"  Recommended follow-up: {f.get('action', '?')} "
                     f"-> {f.get('reason', '')}")

    if result.memory_matches:
        n = len(result.memory_matches)
        lines.append(f"  Episodic recall: {n} similar past candidate(s) in store.")

    return "\n".join(lines)


def _episodic_recall(evidence: Evidence, store: CandidateStore,
                     max_matches: int = 5,
                     sky_tol_arcmin: float = 60.0,
                     rate_tol_arcsec_hr: float = 1.0) -> list[Candidate]:
    """Search the candidate store for prior detections similar to this evidence."""
    if store is None or evidence.ra_deg is None or evidence.dec_deg is None:
        return []
    matches = []
    for c in store:
        dra = (c.ra - evidence.ra_deg) * math.cos(math.radians(evidence.dec_deg))
        ddec = c.dec - evidence.dec_deg
        sep_arcmin = math.hypot(dra, ddec) * 60.0
        if sep_arcmin > sky_tol_arcmin:
            continue
        if evidence.rate_arcsec_hr is not None:
            if abs(c.rate_arcsec_hr - evidence.rate_arcsec_hr) > rate_tol_arcsec_hr:
                continue
        matches.append((sep_arcmin, c))
    matches.sort(key=lambda x: x[0])
    return [m[1] for m in matches[:max_matches]]


def _pareto_front(hypotheses: list[Hypothesis]) -> list[Hypothesis]:
    """Return the Pareto-optimal hypotheses on (posterior, novelty) axes.

    novelty = -log(prior) (rare populations score higher).
    A hypothesis is dominated if there exists another with higher posterior
    AND higher novelty.
    """
    items = []
    for h in hypotheses:
        novelty = -h.prior
        items.append((h, h.posterior, novelty))
    front = []
    for h, p, n in items:
        dominated = False
        for h2, p2, n2 in items:
            if h is h2:
                continue
            if p2 >= p and n2 >= n and (p2 > p or n2 > n):
                dominated = True
                break
        if not dominated:
            front.append(h)
    front.sort(key=lambda h: h.posterior, reverse=True)
    return front


def _recommend_followup(result: InferenceResult,
                        evidence: Evidence) -> dict:
    """Recommend the NEXT observation that would maximally reduce uncertainty.

    Heuristics:
      - High entropy (>1.5 nats): take a 2nd-night confirmation observation.
      - Top hypothesis is high-novelty (rare class): submit to MPC + alert.
      - Top hypothesis is artefact: tag as bogus, no follow-up.
      - Mid-entropy: take a multi-band photometric observation to constrain
        the color-based classification.
    """
    if not result.hypotheses:
        return {"action": "no_action", "reason": "no hypotheses"}
    best = result.best
    entropy = result.entropy

    if best.class_ == "artefact":
        return {
            "action": "discard",
            "reason": f"top hypothesis is {best.label} (artefact); not worth follow-up",
            "expected_info_gain_nats": 0.0,
        }

    if entropy > 1.5:
        return {
            "action": "observe_second_night",
            "reason": (f"posterior is ambiguous (entropy {entropy:.2f} nats); "
                       f"a second-night detection would constrain the orbit"),
            "expected_info_gain_nats": min(entropy, 2.0),
            "observation_target": {
                "ra_deg": evidence.ra_deg,
                "dec_deg": evidence.dec_deg,
                "expected_rate_arcsec_hr": best.predicted_motion_arcsec_hr,
                "expected_displacement_arcmin_per_day": (
                    best.predicted_motion_arcsec_hr * 24.0 / 60.0
                    if best.predicted_motion_arcsec_hr else None),
            },
        }

    if best.class_ == "moving_object" and best.orbital_class in (
            "SEDNOID", "DETACHED", "RESONANT_KBO", "COMET_HYPERBOLIC"):
        return {
            "action": "alert_and_submit_mpc",
            "reason": f"high-novelty {best.orbital_class} candidate at {best.posterior*100:.0f}%",
            "expected_info_gain_nats": entropy,
        }

    if 0.5 < entropy <= 1.5 and not evidence.band_magnitudes:
        return {
            "action": "observe_multiband",
            "reason": ("posterior is moderately confident; multi-band photometry "
                       "would constrain compositional class"),
            "expected_info_gain_nats": entropy * 0.5,
            "observation_target": {
                "ra_deg": evidence.ra_deg,
                "dec_deg": evidence.dec_deg,
                "bands_needed": ["g", "r", "i", "z"],
            },
        }

    return {
        "action": "monitor",
        "reason": f"sufficient confidence ({best.posterior*100:.0f}%) on {best.label}",
        "expected_info_gain_nats": entropy * 0.1,
    }


# ============================================================================
# The engine
# ============================================================================

def infer(evidence: Evidence,
          store: Optional[CandidateStore] = None,
          *,
          class_priors: dict = None,
          artefact_priors: dict = None,
          include_artefact_hypotheses: bool = True,
          scheduler=None) -> InferenceResult:
    """One inference cycle on a piece of evidence. Returns the ranked posterior.

    Args:
      evidence:                Evidence object (any subset of fields).
      store:                   optional CandidateStore for episodic recall.
      class_priors:            override the default class prior fractions.
      artefact_priors:         override the artefact prior fractions.
      include_artefact_hypotheses: if True, also generate spurious-detection
                               hypotheses (recommended -- the cleanest way to
                               flag obvious junk).
      scheduler:               optional PredictiveScheduler -- if provided, the
                               follow-up recommendation uses the learned
                               historical confirmation rates instead of the
                               cold-start heuristic.

    Returns:
      InferenceResult with hypotheses (ranked best first), entropy,
      recommended follow-up action, episodic-memory matches, and a
      human-readable narrative.
    """
    if class_priors is None:
        class_priors = DEFAULT_CLASS_PRIORS
    if artefact_priors is None:
        artefact_priors = ARTEFACT_PRIORS

    hyps = _generate_moving_object_hypotheses(evidence, class_priors)
    if include_artefact_hypotheses:
        hyps.extend(_generate_artefact_hypotheses(evidence, artefact_priors))

    _normalise_posterior(hyps)
    hyps.sort(key=lambda h: h.posterior, reverse=True)

    entropy = _shannon_entropy([h.posterior for h in hyps])
    memory = _episodic_recall(evidence, store) if store is not None else []
    pareto = _pareto_front(hyps)

    result = InferenceResult(
        hypotheses=hyps,
        best=hyps[0] if hyps else None,
        entropy=entropy,
        memory_matches=memory,
        pareto_front=pareto,
    )
    # If a learned scheduler is available, defer to it; else use the heuristic.
    if scheduler is not None and result.best is not None:
        from . import predictive
        ev_class = predictive.classify_evidence(evidence)
        reco = scheduler.recommend(
            evidence_class=ev_class,
            hypothesis_posterior=result.best.posterior,
        )
        result.recommended_followup = {
            "action": reco.action,
            "reason": reco.rationale,
            "expected_info_gain_nats": reco.expected_info_gain_nats,
            "expected_confirmation_prob": reco.expected_confirmation_prob,
            "evidence_class": ev_class,
            "cost": reco.cost,
            "source": "learned_scheduler",
        }
    else:
        result.recommended_followup = _recommend_followup(result, evidence)
        result.recommended_followup["source"] = "heuristic"
    result.narrative = _build_narrative(result, evidence)
    return result


def evidence_from_candidate(c: Candidate) -> Evidence:
    """Convenience: build an Evidence object from a stored Candidate."""
    arc = max(0.0, c.last_seen_mjd - c.first_seen_mjd)
    rms = c.rms_history[-1][1] if c.rms_history else None
    band_mags = c.meta.get("band_magnitudes", {}) if c.meta else {}
    return Evidence(
        mjd=c.last_seen_mjd,
        ra_deg=c.ra, dec_deg=c.dec,
        rate_arcsec_hr=c.rate_arcsec_hr,
        apparent_mag=c.meta.get("apparent_mag") if c.meta else None,
        band_magnitudes=band_mags,
        n_detections=c.n_runs,
        arc_days=arc,
        rms_arcsec=rms,
        orbit_state=c.orbit_state,
        skybot_match_names=c.skybot_names,
    )


def infer_for_store(store: CandidateStore,
                    *, only_discovery: bool = True) -> list[tuple[Candidate, InferenceResult]]:
    """Run the inference engine on every candidate in a store.

    Args:
      only_discovery: when True, only run on discovery_candidates() (no
                      skybot match); when False, run on every candidate.

    Returns:
      List of (candidate, result) pairs, sorted by result.best.posterior * (1 - artefact prob).
    """
    cands = store.discovery_candidates() if only_discovery else list(store)
    out = []
    for c in cands:
        evidence = evidence_from_candidate(c)
        result = infer(evidence, store=store)
        out.append((c, result))

    def _rank(item):
        cand, res = item
        best = res.best
        if best is None:
            return 0.0
        artefact_penalty = 0.0
        for h in res.hypotheses:
            if h.class_ == "artefact":
                artefact_penalty += h.posterior
        return best.posterior * (1.0 - 0.5 * artefact_penalty)

    out.sort(key=_rank, reverse=True)
    return out
