"""Export to / run NASA GMAT for independent cross-validation (MASTER_PLAN §5.2, §12).

GMAT (General Mission Analysis Tool, NASA GSFC, open source) is the industry-standard
mission-analysis tool and our external validation oracle. This module:
  - writes a runnable GMAT .script that propagates a state under a point-mass force
    model (Earth + Sun + Luna) and REPORTS the propagated state to a file, and
  - locates and runs GmatConsole.exe headlessly, parsing the report so the result
    can be compared directly against Ariadne's own propagator (the literal G10 check).
"""
from __future__ import annotations

import os
import subprocess

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(_HERE, "..", "..", ".."))

_TEMPLATE = """%% GMAT script generated by Ariadne (cross-validation export)
%% Epoch: {epoch}   Frame: EarthMJ2000Eq (km, km/s)   Force: point masses Earth+Sun+Luna

Create Spacecraft {name};
GMAT {name}.DateFormat = UTCGregorian;
GMAT {name}.Epoch = '{epoch}';
GMAT {name}.CoordinateSystem = EarthMJ2000Eq;
GMAT {name}.X  = {x:.9f};
GMAT {name}.Y  = {y:.9f};
GMAT {name}.Z  = {z:.9f};
GMAT {name}.VX = {vx:.12f};
GMAT {name}.VY = {vy:.12f};
GMAT {name}.VZ = {vz:.12f};

Create ForceModel FM;
GMAT FM.CentralBody = Earth;
GMAT FM.PointMasses = {{Earth, Sun, Luna}};
GMAT FM.Drag.AtmosphereModel = None;
GMAT FM.SRP = Off;

Create Propagator Prop;
GMAT Prop.FM = FM;
GMAT Prop.Type = RungeKutta89;
GMAT Prop.InitialStepSize = 30;
GMAT Prop.Accuracy = 1e-13;
GMAT Prop.MinStep = 0;

Create ReportFile rf;
GMAT rf.Filename = '{report}';
GMAT rf.WriteHeaders = true;
GMAT rf.Precision = 14;
GMAT rf.ColumnWidth = 28;

BeginMissionSequence;
Report rf {name}.EarthMJ2000Eq.X {name}.EarthMJ2000Eq.Y {name}.EarthMJ2000Eq.Z {name}.EarthMJ2000Eq.VX {name}.EarthMJ2000Eq.VY {name}.EarthMJ2000Eq.VZ;
Propagate Prop({name}) {{{name}.ElapsedDays = {days}}};
Report rf {name}.EarthMJ2000Eq.X {name}.EarthMJ2000Eq.Y {name}.EarthMJ2000Eq.Z {name}.EarthMJ2000Eq.VX {name}.EarthMJ2000Eq.VY {name}.EarthMJ2000Eq.VZ;
"""


def export_gmat_script(path: str, state, epoch_gmat: str, days: float,
                       name: str = "AriadneSat", report_path: str | None = None) -> str:
    """Write a GMAT propagation+report script. state = [x,y,z,vx,vy,vz] (km, km/s)
    in EarthMJ2000Eq; epoch_gmat like '01 Jun 2025 00:00:00.000'."""
    if report_path is None:
        report_path = os.path.splitext(path)[0] + ".report.txt"
    x, y, z, vx, vy, vz = (float(v) for v in state)
    text = _TEMPLATE.format(name=name, epoch=epoch_gmat, days=days, report=report_path,
                            x=x, y=y, z=z, vx=vx, vy=vy, vz=vz)
    with open(path, "w") as f:
        f.write(text)
    return path


def locate_gmat() -> str | None:
    """Find GmatConsole.exe (bundled under tools/, or common install locations)."""
    candidates = [
        os.path.join(REPO_ROOT, "tools", "gmat-R2026a", "bin", "GmatConsole.exe"),
    ]
    for v in ("R2026a", "R2025a", "R2022a"):
        candidates.append(rf"C:\GMAT\{v}\bin\GmatConsole.exe")
        candidates.append(os.path.expanduser(rf"~\GMAT\{v}\bin\GmatConsole.exe"))
    for c in candidates:
        if os.path.exists(c):
            return c
    return None


def parse_report(report_path: str) -> np.ndarray:
    """Parse a GMAT ReportFile of numeric state columns; return rows as (N,6)."""
    rows = []
    with open(report_path) as f:
        for line in f:
            parts = line.split()
            try:
                vals = [float(p) for p in parts]
            except ValueError:
                continue            # header / non-numeric line
            if len(vals) == 6:
                rows.append(vals)
    return np.array(rows)


def run_with_gmat(script_path: str, report_path: str,
                  gmat_console: str | None = None, timeout: int = 300) -> np.ndarray:
    """Run a GMAT script headless with GmatConsole and return the report rows (N,6).

    Raises RuntimeError if GMAT cannot be found or the run fails.
    """
    exe = gmat_console or locate_gmat()
    if exe is None:
        raise RuntimeError("GmatConsole.exe not found (set tools/gmat-R2026a or pass gmat_console)")
    if os.path.exists(report_path):
        os.remove(report_path)
    proc = subprocess.run([exe, os.path.abspath(script_path)],
                          cwd=os.path.dirname(exe), capture_output=True,
                          text=True, timeout=timeout)
    if not os.path.exists(report_path):
        raise RuntimeError(f"GMAT produced no report.\nstdout tail:\n{proc.stdout[-2000:]}")
    return parse_report(report_path)
