"""Export a trajectory to a NASA GMAT script (MASTER_PLAN.md §5.2, §12).

GMAT (General Mission Analysis Tool, NASA GSFC, open source) is our independent
validation oracle. This writes a runnable .script that sets up the spacecraft
initial state (EarthMJ2000Eq), a point-mass force model (Earth, Sun, Luna), and a
Propagate command, so a result can be cross-checked outside Ariadne.

NOTE: the generated script is syntactically standard GMAT but is not executed
here (GMAT is not installed in this environment); it is an export artifact.
"""
from __future__ import annotations

_TEMPLATE = """%% GMAT script generated by Ariadne (cross-validation export)
%% Epoch: {epoch}   State frame: EarthMJ2000Eq (km, km/s)

Create Spacecraft {name};
GMAT {name}.DateFormat = UTCGregorian;
GMAT {name}.Epoch = '{epoch}';
GMAT {name}.CoordinateSystem = EarthMJ2000Eq;
GMAT {name}.X  = {x:.9f};
GMAT {name}.Y  = {y:.9f};
GMAT {name}.Z  = {z:.9f};
GMAT {name}.VX = {vx:.12f};
GMAT {name}.VY = {vy:.12f};
GMAT {name}.VZ = {vz:.12f};

Create ForceModel FM;
GMAT FM.CentralBody = Earth;
GMAT FM.PointMasses = {{Earth, Sun, Luna}};
GMAT FM.Drag.AtmosphereModel = None;
GMAT FM.SRP = Off;

Create Propagator Prop;
GMAT Prop.FM = FM;
GMAT Prop.Type = RungeKutta89;
GMAT Prop.InitialStepSize = 60;
GMAT Prop.Accuracy = 1e-12;

BeginMissionSequence;
Propagate Prop({name}) {{{name}.ElapsedDays = {days}}};
"""


def export_gmat_script(path: str, state, epoch_gmat: str, days: float,
                       name: str = "AriadneSat") -> str:
    """Write a GMAT propagation script. state = [x,y,z,vx,vy,vz] (km, km/s)
    in EarthMJ2000Eq; epoch_gmat like '01 Jun 2025 00:00:00.000'."""
    x, y, z, vx, vy, vz = (float(v) for v in state)
    text = _TEMPLATE.format(name=name, epoch=epoch_gmat, days=days,
                            x=x, y=y, z=z, vx=vx, vy=vy, vz=vz)
    with open(path, "w") as f:
        f.write(text)
    return path
