"""Invariant manifolds of libration-point orbits (MASTER_PLAN.md §3.9).

The stable/unstable manifolds ("tubes") are generated by seeding states along the
Floquet eigenvectors of the monodromy matrix, transported around the orbit by the
STM, then propagated: forward in time for the unstable manifold W^u, backward for
the stable manifold W^s. A spacecraft inside a stable tube is ballistically
captured by the orbit it leads to. These tubes are the transport "highways."
"""
from __future__ import annotations

import numpy as np
from scipy.integrate import solve_ivp

from ..dynamics.cr3bp import eom, eom_stm, jacobi_constant

_INT = dict(method="DOP853", rtol=1e-12, atol=1e-12)


def manifold_eigenvectors(M: np.ndarray):
    """Unstable/stable eigenvectors of the monodromy matrix.

    Returns (v_unstable, v_stable, lambda_unstable). Each eigenvector is real and
    normalized so its position part (first 3 components) has unit norm, so a
    displacement epsilon is a position offset in nondimensional length units.
    """
    vals, vecs = np.linalg.eig(M)
    idx_u = int(np.argmax(np.abs(vals)))
    lam_u = vals[idx_u]
    v_u = np.real(vecs[:, idx_u])
    idx_s = int(np.argmin(np.abs(vals - 1.0 / lam_u)))
    v_s = np.real(vecs[:, idx_s])
    v_u = v_u / np.linalg.norm(v_u[:3])
    v_s = v_s / np.linalg.norm(v_s[:3])
    return v_u, v_s, float(np.real(lam_u))


def manifold_seeds(mu: float, orbit, n_seeds: int = 100,
                   displacement: float = 1e-4, stable: bool = False,
                   branch: int = +1):
    """Seed states for one manifold branch, distributed around the orbit.

    The eigenvector is computed from the monodromy at t=0 and transported to each
    orbit point x(t_i) via the STM Phi(t_i). Returns (seeds (n,6), lambda_u).
    `displacement` is the seed offset in nondimensional length; `branch` = +/-1
    selects the two sides of the manifold. Record `displacement` with any result.
    """
    T = orbit.period
    t_eval = np.linspace(0.0, T, n_seeds + 1)
    y0 = np.concatenate([orbit.s0, np.eye(6).ravel()])
    sol = solve_ivp(eom_stm, (0.0, T), y0, args=(mu,), t_eval=t_eval, **_INT)
    M = sol.y[6:, -1].reshape(6, 6)
    v_u, v_s, lam = manifold_eigenvectors(M)
    v = v_s if stable else v_u

    seeds = np.empty((n_seeds, 6))
    for i in range(n_seeds):
        Xi = sol.y[:6, i]
        Phi_i = sol.y[6:, i].reshape(6, 6)
        d = Phi_i @ v
        d = d / np.linalg.norm(d[:3])
        seeds[i] = Xi + branch * displacement * d
    return seeds, lam


def manifold_trajectory(mu: float, seed, stable: bool = False,
                        t_max: float = 8.0, n: int = 400):
    """Propagate one manifold trajectory (forward for W^u, backward for W^s)."""
    tf = -t_max if stable else t_max
    t_eval = np.linspace(0.0, tf, n)
    sol = solve_ivp(eom, (0.0, tf), np.asarray(seed, float), args=(mu,),
                    t_eval=t_eval, **_INT)
    return sol.t, sol.y


def jacobi_drift(mu: float, seed, stable: bool = False, t_max: float = 8.0) -> float:
    """Max |dC| along a manifold trajectory (integration quality check)."""
    _, Y = manifold_trajectory(mu, seed, stable, t_max, n=200)
    c0 = jacobi_constant(Y[:, 0], mu)
    return float(np.max([abs(jacobi_constant(Y[:, i], mu) - c0)
                         for i in range(Y.shape[1])]))
