"""Seeded replay that PRODUCES every number cited in ONE_FRONTIER_INTEGRATION.md.

The integration document carries no hand-copied numbers: its evidence block is
rendered from ``docs/one_frontier_replay.json``, which this script writes.

    python scripts/one_frontier_replay.py                 # run all, write JSON + doc block
    python scripts/one_frontier_replay.py --check         # re-run deterministic sections
                                                          # and compare with the JSON
    python scripts/one_frontier_replay.py --render-only   # re-render the doc from the JSON

Determinism: every random draw comes from a fixed ``numpy.random.default_rng`` seed,
so test counts, mutant verdicts and simulated trajectory counts are reproducible
exactly. Floating-point discrepancy maxima depend on the BLAS/LAPACK build and are
checked against their declared ceilings, not bit-for-bit. Timings are MEASURED on the
recording machine and are never compared by ``--check``.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

for _var in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ.setdefault(_var, "1")

# BLAS thread counts are read at import, so these imports must follow the setdefault.
import numpy as np  # noqa: E402
import scipy  # noqa: E402
from scipy.linalg import expm, lu_factor, lu_solve  # noqa: E402
from scipy.sparse import csc_matrix, diags  # noqa: E402
from scipy.sparse.linalg import spsolve  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from ariadne.optimize.success_contract import SuccessContract  # noqa: E402

JSON_PATH = ROOT / "docs" / "one_frontier_replay.json"
DOC_PATH = ROOT / "ONE_FRONTIER_INTEGRATION.md"
FOCUSED = "tests/test_success_contract.py"
BEGIN = (
    "<!-- BEGIN GENERATED by scripts/one_frontier_replay.py; edit the script, not this block -->"
)
END = "<!-- END GENERATED -->"

ORACLE_SEED0, ORACLE_INSTANCES, ORACLE_QUERIES = 10_000, 200, 8
ORACLE_CEILING = 1e-12
SIM_SEED, SIM_TRAJECTORIES, SIM_DEADLINE = 20260907, 100_000, 2.0
SIM_W, SIM_FAILURE, SIM_SUCCESS = [[0.0, 3.0], [1.0, 0.0]], [0.2, 0.1], [0.0, 2.0]
BENCH_SEED, BENCH_STATES, BENCH_RETAINED, BENCH_QUERIES, BENCH_REPEATS = 7, 300, 11, 56, 5

#: name -> (exact source text, replacement). Each must match exactly once.
MUTANTS = {
    "stale_model_bypass": (
        "        if current_fingerprint != self.fingerprint:\n"
        '            raise ValueError("STALE_MODEL: recompile the current rates")\n',
        "",
    ),
    "deadline_clock_sign": (
        "G[:n, :n], G[:n, n] = -full, self._b",
        "G[:n, :n], G[:n, n] = full, self._b",
    ),
    "eventual_reported_as_deadline": (
        "bounded = min(max(0.0, cdf), p)",
        "bounded = p",
    ),
    "certificate_on_float_row_sums": (
        # Rebuild the diagonal from the binary64 generator, i.e. the pre-fix defect.
        "            total = sum((a for _, a in row), Fraction(0))\n",
        "            total = q(float(self._M[i, i])) - q(float(self._failure[i]))"
        " - q(float(self._b[i]))\n",
    ),
    "probability_not_clamped": (
        "values = np.clip(h, 0.0, 1.0)",
        "values = h",
    ),
    "deadline_type_unchecked": (
        '            t = _real_scalar(deadline, "deadline")\n',
        "            t = float(deadline)\n",
    ),
}


def oracle_comparisons():
    """Directed random instances: compiler vs independent full dense/exponential solves."""
    max_p = max_deadline = 0.0
    count = deadline_count = 0
    for k in range(ORACLE_INSTANCES):
        r = np.random.default_rng(ORACLE_SEED0 + k)
        n = int(r.integers(3, 40))
        W = r.uniform(0, 1, (n, n)) * (r.random((n, n)) < 0.25)
        np.fill_diagonal(W, 0)
        f, b = r.uniform(0.01, 0.3, n), r.uniform(0, 1, n) * (r.random(n) < 0.5)
        B = sorted({0, *r.choice(n, size=min(n, 4), replace=False).tolist()})
        m = SuccessContract(W, f, b, B)
        for _ in range(ORACLE_QUERIES):
            d = f[B] * r.uniform(0, 0.95, len(B))
            ff = f.copy()
            ff[B] -= d
            A = np.diag(W.sum(1) + ff + b) - W
            h = np.linalg.solve(A, b)
            with_deadline = count % ORACLE_QUERIES == 0
            got = m.evaluate(
                d,
                current_fingerprint=m.fingerprint,
                moments=False,
                deadline=0.5 if with_deadline else None,
            )
            max_p = max(max_p, abs(got["success_probability"] - h[0]))
            if with_deadline:
                oracle = (h - expm(-0.5 * A) @ h)[0]
                max_deadline = max(max_deadline, abs(got["success_before_deadline"] - oracle))
                deadline_count += 1
            count += 1
    return {
        "seeds": f"{ORACLE_SEED0}..{ORACLE_SEED0 + ORACLE_INSTANCES - 1}",
        "comparisons": count,
        "deadline_comparisons": deadline_count,
        "max_abs_probability_discrepancy": max_p,
        "max_abs_deadline_discrepancy": max_deadline,
        "ceiling": ORACLE_CEILING,
    }


def simulation():
    """Event-driven CTMC trajectories, vectorised over trajectories, fixed seed."""
    W, f, s = np.array(SIM_W), np.array(SIM_FAILURE), np.array(SIM_SUCCESS)
    m = SuccessContract(W, f, s, [0])
    v = m.evaluate([0], current_fingerprint=m.fingerprint, deadline=SIM_DEADLINE)
    rng = np.random.default_rng(SIM_SEED)
    N = SIM_TRAJECTORIES
    out_rate, total = W.sum(1), W.sum(1) + f + s
    state, clock = np.zeros(N, dtype=int), np.zeros(N)
    active = np.ones(N, dtype=bool)
    successes = before_deadline = 0
    while active.any():
        idx = np.flatnonzero(active)
        x = state[idx]
        clock[idx] += rng.exponential(1.0 / total[x])
        u = rng.random(len(idx)) * total[x]
        move = u < out_rate[x]
        fail = ~move & (u < out_rate[x] + f[x])
        win = ~move & ~fail
        state[idx[move]] = 1 - x[move]
        successes += int(win.sum())
        before_deadline += int((clock[idx[win]] <= SIM_DEADLINE).sum())
        active[idx[fail | win]] = False
    closed_form = (2 / 3.1) * 3 / (3.2 - 3 / 3.1)

    def z(observed, predicted):
        return (observed - predicted) / math.sqrt(predicted * (1 - predicted) / N)

    pe, pd = v["success_probability"], v["success_before_deadline"]
    return {
        "model": "W=[[0,3],[1,0]], failure=[0.2,0.1], success=[0,2], start 0, deadline 2",
        "seed": SIM_SEED,
        "trajectories": N,
        "eventual_predicted": pe,
        "eventual_closed_form": closed_form,
        "eventual_observed_count": successes,
        "eventual_z": z(successes / N, pe),
        "deadline_predicted": pd,
        "deadline_observed_count": before_deadline,
        "deadline_z": z(before_deadline / N, pd),
    }


def _pytest_counts(workdir, env):
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "-o", "addopts=", FOCUSED],
        cwd=workdir,
        env=env,
        capture_output=True,
        text=True,
    )
    tail = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else proc.stderr[-200:]
    counts = {
        key: int(n) for n, key in re.findall(r"(\d+) (passed|failed|error|errors|skipped)", tail)
    }
    return {
        "passed": counts.get("passed", 0),
        "failed": counts.get("failed", 0),
        "errors": counts.get("error", 0) + counts.get("errors", 0),
        "skipped": counts.get("skipped", 0),
    }


def focused_and_mutants():
    env = {**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}
    focused = _pytest_counts(ROOT, env)
    source = (ROOT / "src/ariadne/optimize/success_contract.py").read_text(encoding="utf-8")
    verdicts = {}
    with tempfile.TemporaryDirectory() as tmp:
        for name, (old, new) in MUTANTS.items():
            if source.count(old) != 1:
                raise SystemExit(f"mutant {name}: anchor text matched {source.count(old)} times")
            dst = Path(tmp) / name
            shutil.copytree(ROOT / "src" / "ariadne", dst / "src" / "ariadne")
            (dst / "tests").mkdir()
            shutil.copy2(ROOT / FOCUSED, dst / FOCUSED)
            target = dst / "src/ariadne/optimize/success_contract.py"
            target.write_text(source.replace(old, new), encoding="utf-8")
            counts = _pytest_counts(dst, {**env, "PYTHONPATH": str(dst / "src")})
            # A mutant is KILLED only by failing assertions; collection errors do not count.
            verdicts[name] = {
                "failing_tests": counts["failed"],
                "errors": counts["errors"],
                "killed": counts["failed"] > 0 and counts["errors"] == 0,
            }
    return focused, verdicts


def benchmark():
    r = np.random.default_rng(BENCH_SEED)
    n, k, Q = BENCH_STATES, BENCH_RETAINED, BENCH_QUERIES
    W = np.zeros((n, n))
    for i in range(n):
        js = r.choice([j for j in range(n) if j != i], size=6, replace=False)
        W[i, js] = r.uniform(0.1, 1.0, 6)
    f = r.uniform(0.01, 0.2, n)
    s = np.zeros(n)
    s[r.choice(n, 10, replace=False)] = r.uniform(0.5, 2.0, 10)
    B = [0, *sorted(r.choice(np.arange(1, n), k - 1, replace=False).tolist())]
    D = [f[B] * r.uniform(0, 0.9, k) * (r.random(k) < 0.5) for _ in range(Q)]
    Ws = csc_matrix(W)
    rows = {
        key: []
        for key in ("prepare", "query", "sparse_resolve", "woodbury_prepare", "woodbury_query")
    }
    disagreement = 0.0
    for _ in range(BENCH_REPEATS):
        t0 = time.perf_counter()
        m = SuccessContract(W, f, s, B)
        t1 = time.perf_counter()
        pc = [m.evaluate(d, current_fingerprint=m.fingerprint)["success_probability"] for d in D]
        t2 = time.perf_counter()
        rowsum = np.asarray(Ws.sum(1)).ravel()
        pr = []
        for d in D:
            ff = f.copy()
            ff[B] -= d
            pr.append(spsolve((diags(rowsum + ff + s) - Ws).tocsc(), s)[0])
        t3 = time.perf_counter()
        lu = lu_factor(np.diag(W.sum(1) + f + s) - W)
        h0 = lu_solve(lu, s)
        U = np.zeros((n, k))
        U[B, range(k)] = 1.0
        Z = lu_solve(lu, U)
        C = Z[B, :]
        t4 = time.perf_counter()
        pw = [h0[0] + Z[0] @ np.linalg.solve(np.eye(k) - d[:, None] * C, d * h0[B]) for d in D]
        t5 = time.perf_counter()
        for key, value in zip(rows, (t1 - t0, t2 - t1, t3 - t2, t4 - t3, t5 - t4), strict=True):
            rows[key].append(value * 1000)
        disagreement = max(
            disagreement,
            *(abs(a - b) for a, b in zip(pc, pr, strict=True)),
            *(abs(a - b) for a, b in zip(pc, pw, strict=True)),
        )
    return {
        "states": n,
        "retained": k,
        "queries": Q,
        "repeats": BENCH_REPEATS,
        "query_includes": "eventual probability + successful-time moments; no certificate, no deadline",
        "median_ms": {key: float(np.median(v)) for key, v in rows.items()},
        "max_disagreement": disagreement,
    }


def environment():
    return {
        "python": platform.python_version(),
        "numpy": np.__version__,
        "scipy": scipy.__version__,
        "platform": platform.platform(),
        "blas_threads": os.environ.get("OPENBLAS_NUM_THREADS"),
    }


def render(data):
    o, sim, b, fo = data["oracle"], data["simulation"], data["benchmark"], data["focused_tests"]
    med = b["median_ms"]
    mutant_lines = "\n".join(
        f"| `{name}` | {'killed' if v['killed'] else '**SURVIVED**'} | {v['failing_tests']} |"
        for name, v in data["mutants"].items()
    )
    N = sim["trajectories"]
    env = data["environment"]
    return f"""{BEGIN}
Recorded with Python {env["python"]}, NumPy {env["numpy"]}, SciPy {env["scipy"]} on `{env["platform"]}`, one BLAS thread. Raw values: `docs/one_frontier_replay.json`.

**Focused suite** (`{FOCUSED}`): {fo["passed"]} passed, {fo["failed"]} failed, {fo["skipped"]} skipped.

**Independent oracles** (seeds {o["seeds"]}): {o["comparisons"]} directed-instance intervention queries against full dense solves, maximum absolute probability discrepancy {o["max_abs_probability_discrepancy"]:.3e}; {o["deadline_comparisons"]} of them also against a dense matrix exponential, maximum deadline discrepancy {o["max_abs_deadline_discrepancy"]:.3e}. Declared ceiling {o["ceiling"]:.0e}.

**Event-driven simulation** ({sim["model"]}; seed {sim["seed"]}, {N:,} trajectories). Eventual success predicted {sim["eventual_predicted"]:.10f} (closed form {sim["eventual_closed_form"]:.10f}), observed {sim["eventual_observed_count"] / N:.5f}, z = {sim["eventual_z"]:+.2f}. Deadline success predicted {sim["deadline_predicted"]:.10f}, observed {sim["deadline_observed_count"] / N:.5f}, z = {sim["deadline_z"]:+.2f}. A synthetic CTMC, not an orbital hardware result.

**Source mutants** (each applied to a disposable copy; killed = failing assertions, collection errors never count):

| mutant | verdict | failing focused tests |
|---|---|---|
{mutant_lines}

**Timing** (MEASURED, machine-dependent, never checked by `--check`): {b["states"]} states, {b["retained"]} retained, {b["queries"]} queries, median of {b["repeats"]} repeats. Preparation {med["prepare"]:.3f} ms, queries {med["query"]:.3f} ms ({b["query_includes"]}); fresh sparse full re-solves {med["sparse_resolve"]:.3f} ms; a conventional prepared Woodbury comparator {med["woodbury_prepare"]:.3f} ms + {med["woodbury_query"]:.3f} ms for eventual probability only. Maximum disagreement {b["max_disagreement"]:.2e}. No universal speed or new-algorithm claim.
{END}"""


def write_doc(data):
    text = DOC_PATH.read_text(encoding="utf-8")
    start, end = text.index(BEGIN), text.index(END) + len(END)
    DOC_PATH.write_text(text[:start] + render(data) + text[end:], encoding="utf-8")


def check(recorded):
    problems = []
    oracle = oracle_comparisons()
    for key in ("comparisons", "deadline_comparisons", "seeds"):
        if oracle[key] != recorded["oracle"][key]:
            problems.append(f"oracle {key}: {oracle[key]} != {recorded['oracle'][key]}")
    for key in ("max_abs_probability_discrepancy", "max_abs_deadline_discrepancy"):
        if not oracle[key] <= ORACLE_CEILING:
            problems.append(f"oracle {key} {oracle[key]} exceeds ceiling {ORACLE_CEILING}")
    sim = simulation()
    for key in ("trajectories", "eventual_observed_count", "deadline_observed_count"):
        if sim[key] != recorded["simulation"][key]:
            problems.append(f"simulation {key}: {sim[key]} != {recorded['simulation'][key]}")
    for key in ("eventual_predicted", "deadline_predicted"):
        if abs(sim[key] - recorded["simulation"][key]) > 1e-12:
            problems.append(f"simulation {key}: {sim[key]} != {recorded['simulation'][key]}")
    return problems


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true")
    group.add_argument("--render-only", action="store_true")
    args = parser.parse_args()
    if args.check:
        problems = check(json.loads(JSON_PATH.read_text(encoding="utf-8")))
        print("\n".join(problems) or "replay matches the recorded deterministic evidence")
        return 1 if problems else 0
    if args.render_only:
        write_doc(json.loads(JSON_PATH.read_text(encoding="utf-8")))
        return 0
    focused, mutants = focused_and_mutants()
    data = {
        "environment": environment(),
        "focused_tests": focused,
        "oracle": oracle_comparisons(),
        "simulation": simulation(),
        "mutants": mutants,
        "benchmark": benchmark(),
    }
    JSON_PATH.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    write_doc(data)
    print(render(data))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
